### ISSUE TITLE
Can't take build with facebook audience network in heyzap

### ISSUE THREAD

**Issue by joy2play** [Heyzap/facebook-audience-network-ane#1]
Hi @KarimP 
we are integrating heyzap ane with admob,applovin and facebook audience network. its working well without facebook audience network. if we integrate facebook audience network below error is throwing when take build. please help us to continue with heyzap. Thanks

Error occurred while packaging the application:

aapt tool failed:C:\Users\dell\AppData\Local\Temp\44a61402-d988-4de2-90b1-f1ec821ebbed\app_entry_res\values\strings.xml:19: error: Resource at app_version appears in overlay but not in the base package; use <add-resource> to add.

**Comment by ekilah** [comment]
@joy2play we're taking a look at this, just a head's up.

**Comment by ekilah** [comment]
@joy2play can you try this SDK build? It's our most recent Beta SDK version 9.2.3 with a fix we hope helps with the error you posted. 

link: https://s3.amazonaws.com/hz-sdk/sdk/heyzap-ads-sdk-9.2.3-FAN_ANE_fix.zip

**Comment by joy2play** [comment]
@ekilah thank you we will check it and update you
